#if defined(ARDUINO_ARCH_RP2040) && !defined(KERMITECORE_MANUAL_STACK_CONFIG)
//default stack configuration for RP2040
#define KEMRITECORE_USE_USBIOCORE_RP2040_ARDUINO_PICO
#define KERMITECORE_USE_FLASH_PERSIST_SECTOR_RP2040_PICO_SDK
#endif
